---
- hosts: "localhost"
  connection: "local"
  gather_facts: true
  become: true
  become_method: "sudo"

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  roles:
    - auto-populate
...
